# Generated by Django 4.1.3 on 2022-11-10 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0002_alter_category_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionsuser",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="transactionsuser",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transactionsuser",
            name="time",
            field=models.TimeField(auto_now=True),
        ),
    ]
